"""empty message

Revision ID: c957a481767e
Revises: dc02648c55dc
Create Date: 2017-09-25 16:29:43.621304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c957a481767e'
down_revision = 'dc02648c55dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'port_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('port_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['port_id'], ['id'])
    # ### end Alembic commands ###
